"""Getty Group pilot customer seed data (Shawn Getty, Calgary AB)"""

GETTY_GROUP_CONTACTS = [
    {
        "id": "contact_jessica_reid",
        "name": "Jessica Reid",
        "title": "Senior Recruiter",
        "org": "Getty Group",
        "phone": "+1-403-555-0101",
        "email": "jessica@getty.group",
        "last_contact": "2026-09-27",
        "status": "active",
        "relationship": "team_member",
        "notes": "Manages recruitment pipeline. Cold reaches out to agents Tue/Thu mornings.",
    },
    {
        "id": "contact_mark_chen",
        "name": "Mark Chen",
        "title": "Real Estate Agent",
        "org": "Getty Group",
        "phone": "+1-403-555-0102",
        "email": "mark.chen@getty.group",
        "last_contact": "2026-09-26",
        "status": "active",
        "relationship": "team_member",
        "notes": "2 new leads qualified this week. Focus: first-time homebuyers.",
    },
    {
        "id": "contact_rachel_martinez",
        "name": "Rachel Martinez",
        "title": "Transaction Coordinator",
        "org": "Getty Group",
        "phone": "+1-403-555-0103",
        "email": "rachel@getty.group",
        "last_contact": "2026-09-28",
        "status": "active",
        "relationship": "team_member",
        "notes": "Coordinating Mitchell closing (expected close: Oct 5). Sarah Johnson title company contact.",
    },
    {
        "id": "lead_chen_family",
        "name": "Mr. & Mrs. Chen",
        "title": "Buyers",
        "city": "Calgary, AB",
        "property_interest": "123 Aspen Ridge Drive (NW Calgary)",
        "budget": "$850k",
        "status": "hot",
        "last_contact": "2026-09-27",
        "next_action": "Showing scheduled",
        "notes": "First-time buyers, looking to close by Q4 2026. Very responsive to follow-ups.",
    },
    {
        "id": "lead_carlos_lopez",
        "name": "Carlos Lopez",
        "title": "Investor",
        "city": "Calgary, AB",
        "property_interest": "Investment property (Commercial or Multi-family)",
        "budget": "$650k+",
        "status": "active",
        "last_contact": "2026-09-25",
        "next_action": "Follow-up call needed",
        "notes": "Silent for 10 days. Interest in 456 Commerce Drive (commercial). Cash buyer.",
    },
    {
        "id": "lead_sarah_mitchell",
        "name": "Sarah Mitchell",
        "title": "Buyer",
        "city": "Calgary, AB",
        "property_interest": "Luxury home, NW/SW Calgary",
        "budget": "$1.2M+",
        "status": "new",
        "last_contact": "2026-09-28",
        "next_action": "Qualification call",
        "notes": "Referral from past client. Relocating from Toronto. Wants heritage property.",
    },
    {
        "id": "cold_recruit_alex_thompson",
        "name": "Alex Thompson",
        "title": "Real Estate Agent (Prospect)",
        "company": "Royal LePage",
        "city": "Calgary, AB",
        "last_contact": "2026-09-15",
        "days_silent": 13,
        "status": "cold_recruit",
        "context": "5 years experience, top producer in brokerage. Mentioned burnout with current mgmt.",
        "personalization": "Growing practice, 40+ leads/year, looking for support team",
    },
    {
        "id": "cold_recruit_priya_patel",
        "name": "Priya Patel",
        "title": "Real Estate Agent (Prospect)",
        "company": "Sotheby's International",
        "city": "Calgary, AB",
        "last_contact": "2026-09-18",
        "days_silent": 10,
        "status": "cold_recruit",
        "context": "Luxury specialist, 8 years experience. Strong Instagram presence.",
        "personalization": "Luxury market focus, looking to expand geographic territory",
    },
    {
        "id": "cold_recruit_david_ng",
        "name": "David Ng",
        "title": "Real Estate Agent (Prospect)",
        "company": "Engel & Völkers",
        "city": "Calgary, AB",
        "last_contact": "2026-09-20",
        "days_silent": 8,
        "status": "cold_recruit",
        "context": "Commercial/Industrial focus, 6 years experience. Growing market share.",
        "personalization": "Commercial expertise, scale into residential market",
    },
]

GETTY_GROUP_CALENDAR_TEMPLATES = {
    "mon": "Team standup 9am, Admin time 10-11am, Showings typically 2-5pm",
    "tue": "Cold recruitment calls 10am-12pm (Jessica's block), Showing appointments",
    "wed": "Content creation time (LinkedIn, market updates), Client calls",
    "thu": "Cold recruitment follow-ups 10am-12pm, Pipeline reviews 2pm",
    "fri": "Weekly close review with Rachel, Team debrief 4pm",
}

GETTY_GROUP_MARKET_CONTEXT = {
    "territory": "Calgary, AB (NW/NE/SW quadrants focus)",
    "market_type": "Residential + Commercial real estate",
    "avg_days_on_market": 35,
    "avg_price_nw": "$650k",
    "recent_trends": "Market cooling, buyer-favoring conditions, interest rate sensitivity",
    "competitors": [
        "Royal LePage (high volume)",
        "Sotheby's International (luxury)",
        "Engel & Völkers (commercial/industrial)",
    ],
}

GETTY_GROUP_CRM_METRICS = {
    "active_deals": 3,
    "pipeline_value": "$2.7M",
    "hot_leads": 2,
    "cold_recruits": 3,
    "team_size": 5,
    "weekly_lead_target": 15,
    "current_week_leads": 7,
}
